language: python

python:
      - "2.7"
      - "3.4"
      - "3.5"

install:
      - pip install -r requirements.txt


script: 

      - py.test test1.py
      - py.test test2.py
      - py.test test3.py
